### ISSUE TITLE
Update to use `id` instead of `self_link`

### ISSUE THREAD

**Issue by rexwangcc** [gatsbysghost/terraform-google-gke-helm-vault#2]
Hi! Thanks for your wonderful TF module! When I'm playing with it, an error around `google-kms` has occurred saying:

```
│ Error: Unsupported attribute
│ 
│   on .terraform/modules/gke-helm-vault/modules/google-kms/keys.tf line 11, in resource "google_kms_crypto_key" "vault_crypto_key":
│   11:   key_ring        = google_kms_key_ring.vault_key_ring.self_link
│ 
│ This object has no argument, nested block, or exported attribute named "self_link".
```

I figured the module needs to be updated to use `id` since `self_link` is deprecated according to [Terraform Google Provider 4.0.0 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/google/latest/docs/guides/version_4_upgrade#resource-google_kms_crypto_key) on resource `google_kms_key_ring`.

(Alternatively, maybe narrow down the google provider versions as something like "version = "~> 3.90.0"?)

**Comment by sendmalwhere** [comment]
Hey there, thanks so much for reaching out!

That’s a great find, and I’m sorry if it caused any breakage for you; I’m traveling today, but I will update the module this evening when I land!

All best,
Scott

**Comment by rexwangcc** [comment]
> That’s a great find, and I’m sorry if it caused any breakage for you; I’m traveling today, but I will update the module this evening when I land!

Thanks for the prompt reply, and no hurry at all! I'm forking it and making changes locally in order to keep exploring this module, will see if that's the only update required here before creating a PR.

_(Have a nice flight!)_
